name: Pull Request Validation

on:
  pull_request:
    branches:
      - main
jobs:
  validate:
   uses: Damasceno-Danilo/qa-shared-workflows/.github/workflows/test.yml@main

    with:
      node-version: '20'
